# AWS playbook
---
- hosts: prod
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  name: configuration play
  user: ec2-user
  pre_tasks:
  - name: 'Install python3'
    raw: 'sudo dnf install -y python3'
  tasks:
  - name: Install apache packages 
    dnf:
      name: httpd
      state: present
  - name: ensure httpd is running
    service:
      name: httpd 
      state: started
  - name: Install Mariadb Server 
    dnf:
      name: mariadb-server
      state: present
  - name: ensure mariadb is running
    service:
      name: mariadb
      state: started
  - name: Install the php Dependencies
    command: "dnf install php php-mysqlnd php-gd php-xml php-mbstring php-json -y"
  - name: Make sure pymysql is present to run mysql commands with ansible
    pip:
      name: pymysql
      state: present
  - name: Create Mysql Database databasewiki
    mysql_db:
      name: databasewiki
      state: present
  - name: create database user admin with password
    mysql_user:
       name: admin
       password: dbadminpass
       priv: '*.*:ALL,GRANT'
       state: present
  - name: Downloading mediawiki-1.34.2.tar.gz and unarchiving
    unarchive:
      src: https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.2.tar.gz
      dest: /var/www/html/
      remote_src: yes
  - name: Create a symbolic link to /var/www/html/mediawiki
    file:
      src: /var/www/html/mediawiki-1.34.2
      dest: /var/www/html/mediawiki
      owner: apache
      group: apache
      state: link
  - name: changing ownership of /var/www/html/mediawiki-1.34.2/
    file:
      path: /var/www/html/mediawiki-1.34.2/
      owner: apache
      group: apache
      recurse: yes
  - name: restarting httpd
    service:
      name: httpd 
      state: restarted
  - name: Adjusting Selinux
    command: restorecon -FR /var/www/html/mediawiki
